apiVersion: apps/v1
kind: Deployment
metadata:
  name:  rock
  namespace: default
  labels:
    app:  rock
spec:
  selector:
    matchLabels:
      app: rock
  replicas: 1
  template:
    metadata:
      labels:
        app:  rock
    spec:
      containers:
      - name:  rock
        image:  jpavia/python:0.0.1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 3000
        env:
        - name: SYMBOL
          valueFrom:
            configMapKeyRef:
              name: rock-config
              key: symbol
        - name: NDAYS
          valueFrom:
            configMapKeyRef:
              name: rock-config
              key: ndays
        - name: APIKEY
          valueFrom:
            secretKeyRef:
              name: rock-secret
              key: api-key
        ports:
        - containerPort:  8080
          name:  rock
      restartPolicy: Always